# Build
FROM python:3.12

WORKDIR /app

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Server
EXPOSE 8000
CMD ["fastapi", "run", "main.py", "--port", "8000"]